version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "11:07"
  - package-ecosystem: "gitsubmodule"
    directory: "xdeadboy666x/ffmpeg-windows-build-helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "11:07"
